GLOBALS:
  image_size: &image_size 224

  input_filename_key: &input_filename_key "filename"
  input_image_key: &input_image_key "image"
  input_target_key: &input_target_key "target"
  input_label_key: &input_label_key "label"

  output_embedding_key: &output_embedding_key "embeddings"

  embedding_size: &embedding_size 256
  head_size: &head_size 256

  num_classes: &num_classes 15
  class_names: &class_names [ # MAX: 0.82554023 [7145 / (7145 + 33810) = 40955]
    'Bread_and_Rolls__Baguette',
    'Bread_and_Rolls__Rolls_frozen',
    'Cake_and_Pastry__Muffins',
    'No_Food__',
    'Pizza__',
    'Pizza_and_Quiche__Onion_Tart', # 5
    'Poultry__Chicken,_whole',
    'Poultry__Chicken_legs',
    'Poultry__Chicken_nuggets',
    'Poultry__Chicken_wings',
    'Side_dishes__Croquettes', # 10
    'Side_dishes__French_fries_frozen',
    'Side_dishes__Wedges',
    'Unknown__Cookies', #13
    'Vegetables__Mediterranean_Vegetables' #14
  ]
  class_names2: &class_names2 [
    'Bread_and_Rolls__Baguette',
    'Bread_and_Rolls__Rolls_frozen',
    'Cake_and_Pastry__Muffins',
    'No_Food__',
    'Pizza__',
    'Pizza_and_Quiche__Onion_Tart',
    'Poultry__Chicken,_whole',
    'Poultry__Chicken_legs',
    'Poultry__Chicken_nuggets',
    'Poultry__Chicken_wings',
    'Side_dishes__Croquettes',
    'Side_dishes__French_fries_frozen',
    'Side_dishes__Wedges',
    'Unknown__Cookies',
    'Vegetables__Mediterranean_Vegetables',

    'ApplePie',
    'Cake',
    'Lasagna',
    'PotatoGratin',
    'Preztel',
    'Quiche',
    'Vegetables',
    'Zucchini'
  ]

  model_name: &model_name "nasnetamobile"
  logdir: &logdir "./logs/cico15_256_triplet_1e-1_radam_plateu_1e-0_l2neck_stratified_doe"

  MAIN_METRIC: &MAIN_METRIC "_avg_top1_acc"
  REDUCE_METRIC: &REDUCED_METRIC "loss"

  num_epochs: &num_epochs 50
  batch_size: &batch_size 256

  lr_top: &lr_top 0.005
  lr_start: &lr_start 1.0
  lr_end: &lr_end 0.000001
  wd: &wd 0.0003

################################################################################

OPTIMIZERS:
  sgd: &sgd
    optimizer: SGD
    lr: *lr_start

  adam: &adam
    optimizer: Adam
    lr: *lr_start
    weight_decay: *wd

  adam_lookahead: &adam_lookahead
    optimizer: Lookahead
    base_optimizer_params:
      optimizer: RAdam
      lr: *lr_start
      weight_decay: *wd

  radam_lookahead: &radam_lookahead
    optimizer: Lookahead
    base_optimizer_params:
      optimizer: RAdam
      lr: *lr_start
      weight_decay: *wd

################################################################################

SCHEDULERS:
  exponential: &exponential
    scheduler: ExponentialLR
    gamma: 0.9

  cosine_warmup_restarts: &cosine_warmup_restarts
    scheduler: CosineAnnealingWarmUpRestarts
    T_0: 200
    T_mult: 2
    eta_max: *lr_top
    eta_min: *lr_end
    T_up: 10
    gamma: 0.5

  lr_on_plateu: &lr_on_plateu
    scheduler: ReduceLROnPlateau
    factor: 0.5
    patience: 5
    threshold: 0.00001

  lr_on_plateu_cutmixup: &lr_on_plateu_cutmixup
    scheduler: ReduceLROnPlateau
    factor: 0.5
    patience: 10
    threshold: 0.00001

  multi_step_scheduler: &multi_step_scheduler
    scheduler: MultiStepLR
    milestones: [20, 40, 70]
    gamma: 0.5

#################################### MODEL #####################################

model_params:
  model: GenericModel
  backbone_params:
    model_name: *model_name
    pretrained: True
    requires_grad: True

#  neck_params:
#    hiddens: [*embedding_size]
#    layer_fn: {"module": "Linear", "bias": True}
#    norm_fn: L2Norm
#    activation_fn: ReLU

  heads_params:
    *output_embedding_key:
      hiddens: [ *embedding_size ]
      layer_fn: { "module": "Linear", "bias": True }
      norm_fn: L2Norm
#      activation_fn: ReLU

##################################### ARGS #####################################

args:
  expdir: "./src/"
  logdir: *logdir
  seed: 69 # KEYWORD, training seed for PyTorch, Numpy, Python and Tensorflow
  per_gpu_scaling: True
  deterministic: True  # KEYWORD, whether to use deterministic CuDNN (Default is True)
  benchmark: True  # KEYWORD, whether to use CuDNN benchmark
  verbose: True  # KEYWORD, whether to display learning information on the console (Default is False)
  check: False  # KEYWORD, if True, then Catalyst does only 3 epochs (to check the performance of the pipeline, by default False)

runner_params:  # OPTIONAL KEYWORD, params for Runner's init
  input_key: [*input_image_key]
  output_key: *output_embedding_key
  input_target_key: *input_target_key

#distributed_params:  # OPTIONAL KEYWORD, params for distributed training and NVIDIA Apex
#  rank: -1  # Rank for distributed training
#  opt_level: O1  # Example for NVIDIA Apex
#  syncbn: True  # KEYWORD, whether to convert BatchNorm to SyncBatchNorm (Default is False)
#  # This level may contain other parameters for the initialization of NVIDIA Apex

#################################### STAGES ####################################

stages:
  data_params:
#    dataset_path: "/workspace/Datasets/CICO1.0/OFR_no_food_modified/initial"
    dataset_path: "/workspace/Datasets/CICO1.5/benchmarking_plan/v3"
    additional_paths: [
      "/workspace/Datasets/CICO1.5/benchmarking_plan/DoEv1_norm",
      "/workspace/Datasets/CICO1.5/benchmarking_plan/DoEv2_norm",
    ]
#    use_one_hot: True
    image_size: *image_size
    batch_size: *batch_size
    num_workers: 12
    class_names: *class_names
    shuffle: True

  criterion_params:
    _key_value: True
    triplet:
      criterion: TripletLoss
      margin: 0.1

  # train head
#  stage1:
#    state_params:
#      num_epochs: *num_epochs
#      main_metric: *MAIN_METRIC
#      minimize_metric: False
#
##    optimizer_params: *radam_lookahead
##    scheduler_params: *lr_on_plateu
#    optimizer_params: *sgd
#    scheduler_params: *exponential
#    callbacks_params:
#      optimizer:
#        callback: OptimizerCallback
#      scheduler:
#        callback: SchedulerCallback
#        reduced_metric: *REDUCED_METRIC
#      saver:
#        callback: CheckpointCallback
#        save_n_best: 3
#
#      criterion_callback:
#        callback: CriterionCallback
#        input_key: *input_target_key
#        output_key: *output_embedding_key
#        criterion_key: "triplet"
#        prefix: *REDUCED_METRIC
#
##      visualization_callback:
##        callback: VisualizationCallback
##        input_keys: *input_image_key
##        concat_images: True
##        denorm_fn: "imagenet"
#
#      benchmarking_callback:
#        callback: BenchmarkingCallback
#        target_key: *input_target_key
#        label_key: *input_label_key
#        filename_key: *input_filename_key
#        embedding_key: *output_embedding_key
#
#        class_names: *class_names2
#        activation: "Softmax"
#
#        enable_benchmark: true
#        benchmark_train_loader: "train"
#        benchmark_test_loader: "valid"
#        benchmark_xlsx: "/workspace/Datasets/CICO1.5/CICO 1.5 benchmarking_plan_v12_FINAL_Working Document v2.xlsx"
#
#        enable_doev1: true
#        doev1_train_loaders: ["train", "valid"]
#        doev1_test_loaders: "extra_DoEv1_norm"
#
#        enable_doev2: true
#        doev2_train_loaders: ["train", "valid"]
#        doev2_test_loaders: "extra_DoEv2_norm"
#        doev2_xlsx: "/workspace/Datasets/CICO1.5/benchmarking_plan/DoEv2_norm/DoE.xlsx"

  infer_cico10:
    data_params:
      dataset_path: "/workspace/Datasets/CICO1.0/OFR_no_food_modified/initial"
      additional_paths: null

    state_params:
      num_epochs: 1

    callbacks_params:
      saver:
        callback: CheckpointCallback
        resume_dir: *logdir
        resume: "checkpoints/best_full.pth"

      benchmarking_callback:
        callback: BenchmarkingCallback
        target_key: *input_target_key
        label_key: *input_label_key
        filename_key: *input_filename_key
        embedding_key: *output_embedding_key

        class_names: *class_names
        activation: "Softmax"
        save_dir: "cico10"
        save_loaders: [ "infer_train", "infer_valid" ]

      # catalyst won't add TensorboardLogger on infer stage by default
      _tensorboard:
        callback: TensorboardLogger
      projector_callback:
        callback: ProjectorCallback
        image_key: *input_image_key
        labels_key: *input_label_key
        embeddings_key: *output_embedding_key
        denorm_fn: "imagenet"
        tag: "cico1.0"
        batch_frequency: 40

  infer_cico15:
    data_params:
      dataset_path: "/workspace/Datasets/CICO1.5/benchmarking_plan/v3"
      additional_paths: null

    state_params:
      num_epochs: 1

    callbacks_params:
      saver:
        callback: CheckpointCallback
        resume_dir: *logdir
        resume: "checkpoints/best_full.pth"

      benchmarking_callback:
        callback: BenchmarkingCallback
        target_key: *input_target_key
        label_key: *input_label_key
        filename_key: *input_filename_key
        embedding_key: *output_embedding_key

        class_names: *class_names
        activation: "Softmax"
        save_dir: "cico15"
        save_loaders: ["infer_train", "infer_valid"]

      # catalyst won't add TensorboardLogger on infer stage by default
      _tensorboard:
        callback: TensorboardLogger
      projector_callback:
        callback: ProjectorCallback
        image_key: *input_image_key
        labels_key: *input_label_key
        embeddings_key: *output_embedding_key
        denorm_fn: "imagenet"
        tag: "cico1.5"
        batch_frequency: 40
